version: "3"
services:
  app:
    container_name: app
    restart: unless-stopped
    build: .
    command: "gunicorn -b 0.0.0.0:8000 app:app"
    ports:
      - "8000:80"
    environment:
      FLASK_ENV: "production"
