version: 2
jobs:
  build:
    docker:
      - image: 'circleci/python:latest'
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: test
          command: pytest